from typing import List

TAXONOMY_VERSION = "v1.0.0"

INCIDENT_CLASSES: List[str] = [
    "BRAKE_SYSTEM_FAILURE",
    "DOOR_MALFUNCTION",
    "HVAC_FAILURE",
    "TRACTION_POWER_LOSS",
    "SIGNAL_COMMUNICATION_FAULT",
    "PANTOGRAPH_DEFECT",
    "WHEEL_FLAT_SPOTTING",
    "TRACK_CIRCUIT_ANOMALY",
    "ONBOARD_FIRE_ALERT",
    "SMOKE_DETECTED",
    "EMERGENCY_BRAKE_ACTIVATION",
    "PASSENGER_ALARM_ACTIVATION",
    "COUPLING_FAILURE",
    "BATTERY_AUX_POWER_FAILURE",
    "CONTROL_SOFTWARE_FAULT",
    "BRAKE_PRESSURE_LEAK",
    "DERAILMENT_INDICATOR_EVENT",
    "OBSTRUCTION_ON_TRACK",
    "OVERHEAT_BEARING_ALERT",
    "UNKNOWN_MECHANICAL_NOISE"
]

BACKWARD_MAPPING = {
    TAXONOMY_VERSION: {label: label for label in INCIDENT_CLASSES}
}

CRITICAL_CLASSES = {
    "ONBOARD_FIRE_ALERT",
    "SMOKE_DETECTED",
    "DERAILMENT_INDICATOR_EVENT",
    "BRAKE_SYSTEM_FAILURE",
    "OBSTRUCTION_ON_TRACK"
}
